In [27]:
import numpy as np 
import pandas as pd

In [28]:
df = pd.read_csv("Exchange_Trade_Data.csv")

df

,Unnamed: 0,Timestamp,Ticker,Price,Volume,Buy/Sell,Trader_ID,Exchange
0,0,2022-01-01 00:00:00,AAPL,150,100,Buy,T1,NYSE
1,1,2022-01-01 00:00:01,GOOGL,2500,200,Sell,T2,NASDAQ
2,2,2022-01-01 00:00:02,MSFT,300,150,Buy,T3,NYSE
3,3,2022-01-01 00:00:03,BTC,155,110,Sell,T4,Binance
4,4,2022-01-01 00:00:04,ETH,2550,210,Buy,T5,Bybit
...,...,...,...,...,...,...,...,...
999995,999995,2022-01-12 13:46:35,XRP,310,160,Sell,T6,Coinbase
999996,999996,2022-01-12 13:46:36,AAPL,150,100,Buy,T1,NYSE
999997,999997,2022-01-12 13:46:37,GOOGL,2500,200,Sell,T2,NASDAQ
999998,999998,2022-01-12 13:46:38,MSFT,300,150,Buy,T3,NYSE
999999,999999,2022-01-12 13:46:39,BTC,155,110,Sell,T4,Binance

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 8 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Unnamed: 0  1000000 non-null  int64
 1   Timestamp   1000000 non-null  object
 2   Ticker      1000000 non-null  object
 3   Price       1000000 non-null  int64
 4   Volume      1000000 non-null  int64
 5   Buy/Sell    1000000 non-null  object
 6   Trader_ID   1000000 non-null  object
 7   Exchange    1000000 non-null  object
dtypes: int64(3), object(5)
memory usage: 61.0+ MB

In [30]:
names = df.groupby("Ticker")["Volume"]